import { Flight } from "../components/FlightCard";

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "1",
    airline: "United Airlines",
    airlineCode: "UA 1234",
    departureTime: "08:00 AM",
    arrivalTime: "11:30 AM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 285,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "2",
    airline: "Delta Airlines",
    airlineCode: "DL 5678",
    departureTime: "09:15 AM",
    arrivalTime: "12:45 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 325,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "3",
    airline: "American Airlines",
    airlineCode: "AA 9012",
    departureTime: "10:30 AM",
    arrivalTime: "04:15 PM",
    duration: "7h 45m",
    durationMinutes: 465,
    stops: 1,
    price: 195,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "4",
    airline: "JetBlue",
    airlineCode: "B6 3456",
    departureTime: "12:00 PM",
    arrivalTime: "03:30 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 295,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "5",
    airline: "Southwest",
    airlineCode: "WN 7890",
    departureTime: "01:45 PM",
    arrivalTime: "07:30 PM",
    duration: "7h 45m",
    durationMinutes: 465,
    stops: 1,
    price: 175,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "6",
    airline: "Alaska Airlines",
    airlineCode: "AS 2345",
    departureTime: "03:00 PM",
    arrivalTime: "06:30 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 315,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "7",
    airline: "United Airlines",
    airlineCode: "UA 6789",
    departureTime: "04:30 PM",
    arrivalTime: "11:00 PM",
    duration: "8h 30m",
    durationMinutes: 510,
    stops: 2,
    price: 155,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "8",
    airline: "Delta Airlines",
    airlineCode: "DL 1111",
    departureTime: "05:15 PM",
    arrivalTime: "08:45 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 385,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "9",
    airline: "American Airlines",
    airlineCode: "AA 2222",
    departureTime: "06:00 PM",
    arrivalTime: "11:45 PM",
    duration: "7h 45m",
    durationMinutes: 465,
    stops: 1,
    price: 225,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "10",
    airline: "JetBlue",
    airlineCode: "B6 3333",
    departureTime: "07:30 PM",
    arrivalTime: "11:00 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 345,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "11",
    airline: "Southwest",
    airlineCode: "WN 4444",
    departureTime: "08:00 AM",
    arrivalTime: "02:30 PM",
    duration: "8h 30m",
    durationMinutes: 510,
    stops: 2,
    price: 145,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "12",
    airline: "Alaska Airlines",
    airlineCode: "AS 5555",
    departureTime: "11:00 AM",
    arrivalTime: "05:15 PM",
    duration: "8h 15m",
    durationMinutes: 495,
    stops: 1,
    price: 205,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "13",
    airline: "United Airlines",
    airlineCode: "UA 6666",
    departureTime: "02:00 PM",
    arrivalTime: "05:30 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 425,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "14",
    airline: "Delta Airlines",
    airlineCode: "DL 7777",
    departureTime: "09:30 AM",
    arrivalTime: "04:00 PM",
    duration: "8h 30m",
    durationMinutes: 510,
    stops: 2,
    price: 165,
    origin: "JFK",
    destination: "LAX",
  },
  {
    id: "15",
    airline: "American Airlines",
    airlineCode: "AA 8888",
    departureTime: "11:30 AM",
    arrivalTime: "03:00 PM",
    duration: "5h 30m",
    durationMinutes: 330,
    stops: 0,
    price: 395,
    origin: "JFK",
    destination: "LAX",
  },
];

export const AVAILABLE_AIRLINES = [
  "United Airlines",
  "Delta Airlines",
  "American Airlines",
  "JetBlue",
  "Southwest",
  "Alaska Airlines",
];
